### ISSUE TITLE
Add support for opening a `File`

### ISSUE THREAD

**Issue by Mek101** [zonyitoo/rust-ini#108]
Currently the [`Ini`](https://docs.rs/rust-ini/latest/ini/struct.Ini.html) struct can only be created anew, from a path or from a string. Could you kindly add a function to open a configuration file from a [`File`](https://doc.rust-lang.org/std/fs/struct.File.html) struct, please?

**Comment by zonyitoo** [comment]
`File` impls `Read`, so you can use [read_from](https://github.com/zonyitoo/rust-ini/blob/371dc9ad2b44afa04d16de38db984f04433659fb/src/lib.rs#L874-L877) .
