### ISSUE TITLE
Unstable features

### ISSUE THREAD

**Issue by ProcTrap** [zonyitoo/rust-ini#11]
Unable to compile as dependency atm 
```/rust-ini-0.4.3/src/lib.rs:48:1: 48:16 error: unstable feature```

**Comment by zonyitoo** [comment]
@ProcTrap Indeed, the `![feature(..)]` won't be allowed in Beta version. Please try to compile it with nightly.

**Comment by ProcTrap** [comment]
Yep, fixed it. Turned out I was indeed using beta without being aware of it.
