### ISSUE TITLE
Reading a Windows-like path doesn't return the path separator.

### ISSUE THREAD

**Issue by aleDsz** [zonyitoo/rust-ini#111]
When reading an ini file with unix-like path separator, it returns the path correctly.

```ini
[data]
test=/path/file.ext
```

```rust
use ini::Ini;

fn main() {
    let conf = Ini::load_from_file("file.ini").unwrap();
    let section = conf.section(Some("data")).unwrap();
    let test = section.get("test").unwrap();

    println!("{:?}", test); // /path/file.ext
}
```

But, if we use the Windows-like path separator, it returns a string with any path separator

```ini
[data]
test=C:\path\file.ext
```

```rust
use ini::Ini;

fn main() {
    let conf = Ini::load_from_file("file.ini").unwrap();
    let section = conf.section(Some("data")).unwrap();
    let test = section.get("test").unwrap();

    println!("{:?}", test); // C:pathfile.ext
}
```

And, with this last, we expect to return a string with double backward slash: `C:\\path\\file.ext`

**Comment by zonyitoo** [comment]
`\` in `ini` is for escaping characters. So in your example, `\p` and `\f` become a single character unit.

You could do this by adding a `\` before `\`:

```ini
[data]
test=C:\\path\\file.ext
```
