### ISSUE TITLE
Whitespace inside quoted values should not be trimmed

### ISSUE THREAD

**Issue by zaneduffield** [zonyitoo/rust-ini#140]
I noticed that quoting a value isn't enough to preserve leading or trailing whitespace.

This code unconditionally trims the value returned by the `parse_value` function
https://github.com/zonyitoo/rust-ini/blob/b2a09b9e334053db70b3f39396169672d05ee88e/src/lib.rs#L1357

One of the reasons quoting is commonly supported in ini files is to allow explicit whitespace.
- https://en.wikipedia.org/wiki/INI_file#Quoted_values

I imagine the solution is to move the `trim` to inside of the `parse_value` and only call it when the value is unquoted.

**Comment by zonyitoo** [comment]
The white spaces are preserved between quotes (`"` and `'`).
https://github.com/zonyitoo/rust-ini/blob/b2a09b9e334053db70b3f39396169672d05ee88e/src/lib.rs#L1548-L1569

**Comment by zaneduffield** [comment]
Outside of that function, the value is trimmed
https://github.com/zonyitoo/rust-ini/blob/b2a09b9e334053db70b3f39396169672d05ee88e/src%2Flib.rs#L1357

When I notice this issue I was only using escaped whitespace (`\r\n`, for example). That may be relevant.

**Comment by zonyitoo** [comment]
Ah, right. I couldn't remember why we should trim the value after it was parsed.

**Comment by zaneduffield** [comment]
But you think that there might be a good reason to do so?
