### ISSUE TITLE
Sectionless files are not supported

### ISSUE THREAD

**Issue by mkpankov** [zonyitoo/rust-ini#16]
Seems `rust-ini` is unable to parse an INI that has no sections and just lists key-value pairs.

I figured it's possible to work around this using `.general()` section, but this solution limits interoperability.

I have external INI produced by another program in format that has no sections whatsoever, and `rust-ini` is unable to read that file.

I'd like to be able to refer to any 'top-level' non-sectioned keys.

**Comment by zonyitoo** [comment]
I am sure that it was always supported.

Please pull the latest commits in the master. I have changed some APIs. For you use cases, please just use `conf.section(None)`, it will return the general section.

Also, there is a helper function, `conf.general_section()`.

**Comment by zonyitoo** [comment]
In the previous version, I use `@General` as the general section's key. But I think it would be better to use `Option<String>` as key to distinguish general section from normal section.

**Comment by mkpankov** [comment]
Thanks, got it!

New version does indeed work as intended.
