### ISSUE TITLE
cargo build error

### ISSUE THREAD

**Issue by soulfly** [zonyitoo/rust-ini#18]
I got this after 'cargo build' : 

     Updating registry `https://github.com/rust-lang/crates.io-index`
     Downloading rust-ini v0.8.0
     Compiling log v0.3.1
     Compiling rust-ini v0.8.0
     /Users/igork/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-ini-0.8.0/src/lib.rs:46:1: 46:16 error: unstable feature
    /Users/igork/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-ini-0.8.0/src/lib.rs:46 #![feature(io)]
                                                                                                 ^~~~~~~~~~~~~~~
    note: this feature may not be used in the stable release channel
    error: aborting due to previous error
    Could not compile `rust-ini`.

**Comment by zonyitoo** [comment]
Ah, you must use the stable version of rustc.

What's your rustc version?

**Comment by soulfly** [comment]
rustc --version 

     rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)

**Comment by zonyitoo** [comment]
Ok.. You may need the latest stable rustc, or nightly.

**Comment by soulfly** [comment]
You mean 1.1 Stable ?

**Comment by zonyitoo** [comment]
Worth trying, or you could just use nightly directly.

**Comment by aporo69** [comment]
Hi, I have the same issue with the latest stable version of Rust (1.2.0) and rust-ini 0.8.1.

Here's my build error log:
```
Fresh libc v0.1.10
   Compiling rust-ini v0.8.1
     Running `rustc /home/USER/.cargo/registry/src/github.com-0a35038f75765ae4/rust-ini-0.8.1/src/lib.rs --crate-name ini --crate-type lib -g -C metadata=baad31b2a93d7137 -C extra-filename=-baad31b2a93d7137 --out-dir /home/USER/workspace/tutorial_rust-ini/target/debug/deps --emit=dep-info,link -L dependency=/home/USER/workspace/tutorial_rust-ini/target/debug/deps -L dependency=/home/USER/workspace/tutorial_rust-ini/target/debug/deps --extern log=/home/USER/workspace/tutorial_rust-ini/target/debug/deps/liblog-f18a3e885170bd3f.rlib -Awarnings`
       Fresh log v0.3.2
/home/USER/.cargo/registry/src/github.com-0a35038f75765ae4/rust-ini-0.8.1/src/lib.rs:46:1: 46:16 error: #[feature] may not be used on the stable release channel
/home/USER/.cargo/registry/src/github.com-0a35038f75765ae4/rust-ini-0.8.1/src/lib.rs:46 #![feature(io)]
                                                                                        ^~~~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `rust-ini`.

Caused by:
  Process didn't exit successfully: `rustc /home/USER/.cargo/registry/src/github.com-0a35038f75765ae4/rust-ini-0.8.1/src/lib.rs --crate-name ini --crate-type lib -g -C metadata=baad31b2a93d7137 -C extra-filename=-baad31b2a93d7137 --out-dir /home/USER/workspace/tutorial_rust-ini/target/debug/deps --emit=dep-info,link -L dependency=/home/USER/workspace/tutorial_rust-ini/target/debug/deps -L dependency=/home/USER/workspace/tutorial_rust-ini/target/debug/deps --extern log=/home/USER/workspace/tutorial_rust-ini/target/debug/deps/liblog-f18a3e885170bd3f.rlib -Awarnings` (exit code: 101)
bash: exit 101   cargo build --verbose
```

Do you have any version working with the actual stable or is it for nighly builds only?

Best regards.

**Comment by zonyitoo** [comment]
@aporo69 Because the `.chars()` method is unstable, so this crate must enable the `io` feature.

**Comment by mkpankov** [comment]
Is is possible to avoid the `.chars()`? It looks tiny amount of code to re-implement inside of rust-ini but I currently have to switch to nightly already because of this.

**Comment by zonyitoo** [comment]
Ok, working on this. Let me see how to get rid of the `.chars`. :)

**Comment by zonyitoo** [comment]
Hey guys, please test this commit if it works. I will push a new version to crates.io. :)

**Comment by mkpankov** [comment]
@zonyitoo Thanks a lot, works for me!
