### ISSUE TITLE
`Ini::section` and `Ini::index` abuse a soundness hole

### ISSUE THREAD

**Issue by arielb1** [zonyitoo/rust-ini#19]
The relevant code is
```Rust
    pub fn section<'a: 'i, 'p>(&'a self, name: Option<&'p str>) -> Option<&'i Properties<'pk, 'pv>> {
        self.sections.get(&name.map(|s| s.into()))
    }
```

You access the `sections` HashMap, which has the type `&'a HashMap<Option<Cow<'i, str>, _>`, and you try to access it with an `Option<Cow<'p, str>>`. The lifetime mismatch is not detected by Rust 1.5, but will be detected by future versions of rustc.

`index` has a similar problem.

The only fix I am aware of is to turn the `Cow` to an owned one.

**Comment by zonyitoo** [comment]
Hmm, you are correct. Would you fire an PR?

**Comment by arielb1** [comment]
@zonyitoo 

Would adding an allocation there be too bad?

**Comment by zonyitoo** [comment]
It shouldn't be too complicated to make all data to be owned by the Ini instance. Just replace all `Cow` to their owned version should be Ok.

I use `Cow` here just for learning how lifetime works (This is my first Rust project).

**Comment by zonyitoo** [comment]
I am going to fix this.
