### ISSUE TITLE
fails on .ini files with comment in the final line

### ISSUE THREAD

**Issue by dario23** [zonyitoo/rust-ini#20]
minimal failing example:

    // parse.rs
    extern crate ini;
    use ini::Ini;
      
      pub fn main() {
    
      let conf = Ini::load_from_file("fvwm.desktop");
      match conf {
          Ok(c) => {
               println!("ok for file {}", f);
               for (sec, prop) in c.iter() {
                  println!("Section: {:?}", sec);
                  for (key, value) in prop.iter() {
                      println!("{:?}:{:?}", key, value);
                  }
              }
          }
          Err(e) => {
              println!("error in file {}: {}", f, e);
          }
      }

and input file (in the same directory)

    ## fvwm.desktop ##
    
    [Desktop Entry]
    Name=Fvwm
    Comment=Fvwm
    Exec=fvwm2
    Terminal=False
    TryExec=fvwm2
    Type=Application
    
    [Window Manager]
    SessionManaged=true
    
    ##

then doing

  cargo run

fails with error

    error: 14:0 Expecting "[Some('=')]" but found EOF.

now github issue markdown doesn't do line numbers, but that's the last line. removing it makes everything work.

i haven't looked into the source yet, but if you need i could look into providing a patch sometime around the weekend maybe.

**Comment by zonyitoo** [comment]
Err, well, `rust-ini` supports comments begins with `;` not `#`, but I am going to support this feature ...

**Comment by zonyitoo** [comment]
`## fvwm.desktop ##` this line should failed to parse, too.

**Comment by dario23** [comment]
ah, i see.. sorry i didn't check comment character before.

i notice now that other files with '#' as the comment sign wrap the "item name" over to the next line if there's no '=' sign in the line, or else take "# name" to be the name

thanks for supporting this as a new feature though :-)

**Comment by zonyitoo** [comment]
It should fixed this issue, please test this commit.

**Comment by dario23** [comment]
works :-) :+1:
