### ISSUE TITLE
Multiline options panic if they are the last ones

### ISSUE THREAD

**Issue by dwiesent** [zonyitoo/rust-ini#21]
Hi,

The following ini file should work, but panics with an Err value: Error { line: 3, col: 0, msg: "Expecting "[Some('=')]" but found EOF." }
```ini
[Section]
Option=This is an example
  text going over several lines.
```

If I add another (one line) option at the very end, it works again.

**Comment by zonyitoo** [comment]
Errr, I don't think this library supports multiline options currently.
