### ISSUE TITLE
make Ini implement IntoIterator

### ISSUE THREAD

**Issue by tshepang** [zonyitoo/rust-ini#26]
This is to avoid having to call `.iter()` when iterating.

**Comment by zonyitoo** [comment]
That would cause `Ini` to be moved when you iterating on it.

**Comment by tshepang** [comment]
If you don't want it moved, you'd do `for (sec, prop) in &foo`. Would that not work?

**Comment by zonyitoo** [comment]
Oh... I see .. That is a good way to go.

**Comment by zonyitoo** [comment]
Already implemented, please test it and give me feedbacks! Thanks for your issue!
I will publish it if you think it is Ok.

**Comment by tshepang** [comment]
wow, that was way too quick!

**Comment by tshepang** [comment]
works well
