### ISSUE TITLE
Special characters (#) are not parsed properly

### ISSUE THREAD

**Issue by peteruhnak** [zonyitoo/rust-ini#31]
Hi,

It seems that if the value contains a special character, it is trimmed. E.g.

```
[playlist]
numberofentries=1
File1=somepath
Title1=Something: Name (#1  ): More / text.
Version=2
```

The `Title1` value will be read only as `Something: Name (`.

If I compare the output to other languages' libraries (python, smalltalk), the value is (correctly) parsed in full.

Thanks!

**Comment by zonyitoo** [comment]
The line that begins with `#` is a comment.

**Comment by peteruhnak** [comment]
Well, the standard comment character for ini files is normally a semicolon `;`.

The hash sign varies by implementation, but it seems that some libraries do not recognize it as a trailing comment https://stackoverflow.com/questions/1378219/do-standard-windows-ini-files-allow-comments

```py
python -c 'import iniparse; print iniparse.INIConfig(file("playlist.pls")).playlist.Title1'
Something: Name (#1  ): More / text.
```

but some do https://github.com/TwP/inifile#comments-1

Maybe such option could be configurable?

**Comment by zonyitoo** [comment]
Hmm, reasonable.

We may need a
```rust
struct SyntaxConfig {
    comment_style: CommentStyle,
}

enum CommentStyle {
    Standard,
    HashSign,
}
```

**Comment by zonyitoo** [comment]
BTW, I would prefer the way that `TwP` is using.

**Comment by zonyitoo** [comment]
Or we could simplified it to:

```ini
# This is a comment
Key = Value   # This is not a comment
```

**Comment by dns2utf8** [comment]
I implemented it, please let me know if it respects the spec.

**Comment by zonyitoo** [comment]
Works fine, I will publish it later today if no one complain, thanks!

**Comment by dns2utf8** [comment]
You are welcome :blush:
