### ISSUE TITLE
Hi, Can you add new features?

### ISSUE THREAD

**Issue by y6cmE** [zonyitoo/rust-ini#36]
Hi, can you add two features? Modify the content, increase the content, such as:

i["User", "name"] the original value is "hi", change its value to "hey" and writed file

Add one at the end of the conf.ini file
[add]
Name=ok

This user is more convenient to operate ini? Thank you!

**Comment by zonyitoo** [comment]
Well, it is impossible to write things like

```rust
i["User", "name"]
```

in Rust. It can only be

```rust
i[("User", "name")]
```

And I think it is ugly.

**Comment by zonyitoo** [comment]
Do you mean this `set_to` function?
https://github.com/zonyitoo/rust-ini/blob/master/src/ini.rs#L258

Can it solve your problem?

**Comment by y6cmE** [comment]
Sorry, this is all my fault! I tried, with_section (section).Set (key, value); can work, thank you!
