### ISSUE TITLE
Order is not the same every run

### ISSUE THREAD

**Issue by inv2004** [zonyitoo/rust-ini#39]
I iter() over sections. Expected that order will be the same like in file, but it different every time.

Is it expected behavior for sections?

**Comment by zonyitoo** [comment]
Because properties are stored in a hash map.

**Comment by inv2004** [comment]
Are there any plans to replace it with hashmap which can save order?

**Comment by zonyitoo** [comment]
Any reason for this?

**Comment by inv2004** [comment]
Sometimes it is useful to use sections to describe some list, for example:
[IBM]
url=ibm.com
[MS]
url=ms.com
[ORACLE]
url=oracle.com

And, because it is list, you expect it will be processes in order.
Of course it is possible to add something like order=1,2,3 field, but natural order in ini also could work.

**Comment by zonyitoo** [comment]
That is not guaranteed by any INI specification. Could you tell me which INI implementation preserves sections' order?? And if you want to have some kind of order, order by what?

1. Order section keys by lexical order
2. Order section by insertion order

And, should we order properties, too?

**Comment by inv2004** [comment]
Hello, Thank you for clarification. I found that some implementations _can_ save INI order, but default windows internal implementation does not support it. That is why it is not correct to rely on it. I will use "order" parameter.
