### ISSUE TITLE
Cannot correctly parse value with partial quoting

### ISSUE THREAD

**Issue by blahgeek** [zonyitoo/rust-ini#45]
e.g.

```
[Section]
A="quote" arg0
B=b
```

The parsed value for key `A` is `quote` (`quote arg0` or `"quote" arg0` is expected), and the parsed value for key `B` is empty (`b` is expected).

**Comment by zonyitoo** [comment]
I think the expected result is `quote arg0`.

**Comment by zonyitoo** [comment]
Quick fix. Is that work for you?

**Comment by blahgeek** [comment]
Hi @zonyitoo , thanks for the quick reply and fixing!

Now that I've thought about it, the `"quote" arg0` parsing result makes more sense to me, especially for linux .desktop files, like:

```
[Desktop Entry]
Exec = "/path/to/exe with space" arg
```

The value for `Exec` key should be `"/path/to/exe with space" arg`, and it's the shell's responsibility to further parse it into `["/path/to/exe with space", "arg"]`. It's documented in the [Desktop Entry Specification](https://developer.gnome.org/desktop-entry-spec/). Though I'm not sure about general INI file format specification.

Maybe add an option to support both?

**Comment by zonyitoo** [comment]
Basic INI file format does not support `"` and `'`. Everything is a string.
Maybe I can add an option to disable quoting support?

**Comment by blahgeek** [comment]
Ok that would be great.

**Comment by zonyitoo** [comment]
@blahgeek Please test the latest commit.

**Comment by zonyitoo** [comment]
Of course. I will do it tonight.

**Comment by zonyitoo** [comment]
It should work now.
