### ISSUE TITLE
Support for duplicate sections

### ISSUE THREAD

**Issue by mikroskeem** [zonyitoo/rust-ini#49]
Let's say I want to parse such ini file:
```ini
[Peer]
foo = a
bar = b

[Peer]
foo = c
bar = d

[Peer]
foo = e
bar = f
```
Currently I can only access last section's values when I iterate over whole ini file.

**Comment by zonyitoo** [comment]
What's your expected behavior? Value of `Peer.foo` should be unique in the whole file.

**Comment by mikroskeem** [comment]
I'm trying to parse [WireGuard](https://www.wireguard.com)'s configuration file, which looks similar to one I provided.

I only need to iterate over file to access all peer's properies.

**Comment by zonyitoo** [comment]
That's ... unexpected.
It will need a breaking change to support this feature, which I don't think is supported by the INI parsers in the other languages...

**Comment by mikroskeem** [comment]
Alright, I'll cook my own parser instead then :smile:

You may leave the issue open if you are up to implement this feature.

**Comment by zonyitoo** [comment]
Already pushed to `master` ... after 2 years.

**Comment by zonyitoo** [comment]
Released in `v0.15.0`

**Comment by whmountains** [comment]
Awesome!  Just in time for the Wireguard configuration tool I'm building.

**Comment by mikroskeem** [comment]
Ah yes, I was doing the same but got nowhere :)

**Comment by theonewolf** [comment]
Huge +1 for this one!  Thanks @zonyitoo!!!
