### ISSUE TITLE
Array Support and Iterator of that

### ISSUE THREAD

**Issue by cyberpunkbln** [zonyitoo/rust-ini#55]
Hello,
a little feature request. The support of array in ini-files will be nice:

```
[section]
option[]=1
option[]=2
option[]=3
option[]=4
```

ini["section"]["option"][0]
ini["section"]["option"][1]
...

And an iterator over that array will be nice, too.

for test in ini[section][option].iter()

thx

**Comment by zonyitoo** [comment]
Well, can you provide any documentation of this Array syntax?

**Comment by cyberpunkbln** [comment]
@zonyitoo Hi, i think it''s not an official documentation but under php this solutions will be provided for arrays in ini-files.

[https://stackoverflow.com/questions/11213641/php-ini-creating-arrays-with-parse-ini-file](https://stackoverflow.com/questions/11213641/php-ini-creating-arrays-with-parse-ini-file)

The internal php ini parser has this ability and i don't know if this is official ini-parsing or an old php hack for php-ler.

thx for investigate. A interator -> HashMap will be great.

**Comment by zonyitoo** [comment]
This would lead to a breaking change. Because values in section is a Key-Value pair (string -> string).

**Comment by cyberpunkbln** [comment]
@zonyitoo I'll try it the next days, thx.

**Comment by cyberpunkbln** [comment]
Hello,
is that right that only double keys will be accepted?

When i use an key like that Exe[] i became an array with name "Exe[]"?

But for now when i have some Keys with the same Key-Name i became an MultiMap, thats cool enough for an Ini-Parsing Library:).

You can go to 0.14.0 :)

**Comment by cyberpunkbln** [comment]
And please can you put some Example of that in the readme. This will be nice.

**Comment by cyberpunkbln** [comment]
I have following ini
```
 [Test]
 exe=1
 exe=2
 exe=3
 exe=4
 exe=5
 exe=6
 exe1="fooBar"
```

When i load the ini and `let section = ini.section(Some("Portal")).unwrap();` and then `println!("{:?}", section.get("exe").unwrap());` i only became the "1" and when i use len() i became an 1 for only one entry in the multimap.

when i print the whole section i became:

`{"exe": ["1", "2", "3", "4", "5", "6"], "exe1": ["fooBar"]}`

section["exe"] seems only be a string?

**Comment by zonyitoo** [comment]
Please read the example about `get` and `get_vec`: https://crates.io/crates/multimap

**Comment by cyberpunkbln** [comment]
Thx good tip, All is clear and all functioned very well at this point, thx for the the addition to your crate.
