### ISSUE TITLE
Creating new config with_section(None) seems broken

### ISSUE THREAD

**Issue by clunion** [zonyitoo/rust-ini#67]
the example code below 
Usage 
   Create a Ini configuration file.
results in the following error:
error[E0283]: type annotations needed
96 |     conf.with_section(None)
    |          ^^^^^^^^^^^^ cannot infer type for type parameter `S` declared on the associated function `with_section`
   |
   = note: cannot satisfy `_: std::convert::Into<std::string::String>`

Please excuse if the fault is on my side, 
i am a bit new to Rust, thus i have no idea yet how to suggest a fix.

**Comment by zonyitoo** [comment]
```rust
conf.with_section(None::<String>);
```

May be I can add a default type for generic parameter `S`.

**Comment by zonyitoo** [comment]
Add a new function

```rust
conf.with_general_section()
```
