### ISSUE TITLE
a way to remove a key-value pair

### ISSUE THREAD

**Issue by tshepang** [zonyitoo/rust-ini#68]
Using the following as an example
```ini
[section]
key = value-1
key = value-2
```
How do I remove `key = value-2`?

Closest I could get is `Properties::remove`, but that removes the first pair (according to docs).

**Comment by zonyitoo** [comment]
According to [ListOrderedMultimap.remove](https://docs.rs/ordered-multimap/0.2.4/ordered_multimap/list_ordered_multimap/struct.ListOrderedMultimap.html#method.remove)'s doc, `remove` will remote **all** values but return the first one.

I don't see any APIs that fulfill your requirements.

**Comment by zonyitoo** [comment]
You may have to use `remove_all`.

**Comment by tshepang** [comment]
Ended up with something like:
```rust
let v = prop.remove_all(key).collect::<Vec<String>>();
for value in v.into_iter() {
    if value == "value-2" {
        continue;
    }

    prop.append(key.clone(), value);
}
```
Thanks much
