### ISSUE TITLE
Support UTF-8 BOM

### ISSUE THREAD

**Issue by PikminGuts92** [zonyitoo/rust-ini#79]
I'm currently unable to parse an ini that contains a starting UTF-8 BOM (byte order marker) `EF BB BF`. Since it's not whitespace, the parser treats it as beginning of a key.

Example:
```
ï»¿[song]
artist=Billy Joel
name=Piano Man
year=1973
```

This causes the first section marker to be ignored and instead interpreted as a section-less key of `[song]\r\nartist`.
https://github.com/zonyitoo/rust-ini/blob/062bff96ba27327158a036a815a0816c7a03fbb8/src/lib.rs#L1011-L1018

**Comment by zonyitoo** [comment]
One simple solution, you can just `skip()`s the first 3 bytes of the `File` and let `Ini` parses the rest of the file contents:
https://github.com/zonyitoo/rust-ini/blob/062bff96ba27327158a036a815a0816c7a03fbb8/src/lib.rs#L796-L799

**Comment by PikminGuts92** [comment]
> 
> 
> One simple solution, you can just `skip()`s the first 3 bytes of the `File` and let `Ini` parses the rest of the file contents:

Thanks. That's what I'll do for now. Previously I was using `Ini::load_from_file` for parsing but I'll switch to your suggestion and skip the BOM beforehand if detected.

**Comment by zonyitoo** [comment]
UTF-8 with BOM is not a common case in Rust. If we have to support BOM, then how about UTF-16? .. Hmm.

**Comment by PikminGuts92** [comment]
That's for you to decide. I wanted to put the issue out there in case others run into it. I only stumbled across it because presumably some text editor that saved the `.ini` file I was parsing prefixed the BOM.

**Comment by zonyitoo** [comment]
Please test if this commit works for you.

**Comment by PikminGuts92** [comment]
> 
> 
> Please test if this commit works for you.

Can confirm it works, thanks. 👍

**Comment by zonyitoo** [comment]
Good. Publish right now.
